pipeline:

  build:
    image: banian/node
    commands:
        - NODE_ENV=production yarn

  publish:
    image: plugins/docker
    mirror: http://mirror.docker.cloud.aut.ac.ir
    registry: registry.docker.cloud.aut.ac.ir
    repo: registry.docker.cloud.aut.ac.ir/internet/internet
    secrets: [ docker_username, docker_password ]
    tag: latest
    squash: true
    when:
      branch: master
      event: push